# NumPy Assignment - Basic Operations and Mathematical Functions

## Q1: Questions on Basic NumPy Array

### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
# reverse it
r = np.flip(arr)
print("Original array:", arr)
print("Reversed array:", r)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


### (b) Flatten the NumPy array using two different methods

In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:")
print(array1)

# Method 1: Using flatten()
f_a1 = array1.flatten()
print("\nFlattened using flatten():", f_a1)

# Method 2: Using ravel()
f_a2 = array1.ravel()
print("Flattened using ravel():", f_a2)

Original array:
[[1 2 3]
 [2 4 5]
 [1 2 3]]

Flattened using flatten(): [1 2 3 2 4 5 1 2 3]
Flattened using ravel(): [1 2 3 2 4 5 1 2 3]


### (c) Compare the NumPy arrays

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print(f"\nAre arrays equal? {np.array_equal(arr1, arr2)}")

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[1 2]
 [3 4]]

Are arrays equal? True


### (d) Find the most frequent value and their indices

In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
from collections import Counter

# For array x
counts_x = Counter(x)
most_common_x = counts_x.most_common(1)[0]
most_frequent_value_x = most_common_x[0]
indices_x = np.where(x == most_frequent_value_x)[0]

print(f"Array x: {x}")
print(f"Most frequent value: {most_frequent_value_x}")
print(f"Indices of most frequent value: {indices_x}")

# For array y
counts_y = Counter(y)
most_common_y = counts_y.most_common(1)[0]
most_frequent_value_y = most_common_y[0]
indices_y = np.where(y == most_frequent_value_y)[0]

print(f"\nArray y: {y}")
print(f"Most frequent value: {most_frequent_value_y}")
print(f"Indices of most frequent value: {indices_y}")

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices of most frequent value: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices of most frequent value: [0 1 2]


### (e) Matrix operations - Sum calculations

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Matrix gfg:")
print(gfg)

print(f"\ni. Sum of all elements: {np.sum(gfg)}")
print(f"ii. Sum row-wise: {np.sum(gfg, axis=1).flatten()}")
print(f"iii. Sum column-wise: {np.sum(gfg, axis=0).flatten()}")

Matrix gfg:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

i. Sum of all elements: 45
ii. Sum row-wise: [[14 16 15]]
iii. Sum column-wise: [[20  9 16]]


### (f) Matrix operations - Linear algebra

In [7]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Matrix n_array:")
print(n_array)

print(f"\ni. Sum of diagonal elements: {np.trace(n_array)}")

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"\nii. Eigenvalues:")
print(eigenvalues)

print(f"\niii. Eigenvectors:")
print(eigenvectors)

print(f"\niv. Inverse matrix:")
print(np.linalg.inv(n_array))

print(f"\nv. Determinant of the matrix: {np.linalg.det(n_array):.2f}")

Matrix n_array:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

i. Sum of diagonal elements: 176

ii. Eigenvalues:
[98.16835147 28.097044   49.73460452]

iii. Eigenvectors:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

iv. Inverse matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

v. Determinant of the matrix: 137180.00


### (g) Matrix multiplication and covariance

In [8]:
# i. First set of matrices
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print("i. First set of matrices:")
print("p =", p1)
print("q =", q1)
print("\nMatrix multiplication (p @ q):")
print(np.dot(p1, q1))
print("\nCovariance between matrices:")
print(np.cov(p1.flatten(), q1.flatten()))

# ii. Second set of matrices
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

print("\n\nii. Second set of matrices:")
print("p =", p2)
print("q =", q2)
print("\nMatrix multiplication (p @ q):")
print(np.dot(p2, q2))
print("\nCovariance between matrices:")
print(np.cov(p2.flatten(), q2.flatten()))

i. First set of matrices:
p = [[1 2]
 [2 3]]
q = [[4 5]
 [6 7]]

Matrix multiplication (p @ q):
[[16 19]
 [26 31]]

Covariance between matrices:
[[0.66666667 1.        ]
 [1.         1.66666667]]


ii. Second set of matrices:
p = [[1 2]
 [2 3]
 [4 5]]
q = [[4 5 1]
 [6 7 2]]

Matrix multiplication (p @ q):
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance between matrices:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]

p = [[1 2]
 [2 3]]
q = [[4 5]
 [6 7]]

Matrix multiplication (p @ q):
[[16 19]
 [26 31]]

Covariance between matrices:
[[0.66666667 1.        ]
 [1.         1.66666667]]


ii. Second set of matrices:
p = [[1 2]
 [2 3]
 [4 5]]
q = [[4 5 1]
 [6 7 2]]

Matrix multiplication (p @ q):
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance between matrices:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


### (h) Inner, outer and cartesian products

In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Matrix x:")
print(x)
print("\nMatrix y:")
print(y)

# Inner product
print("\nInner product:")
print(np.inner(x, y))

# Outer product (using flattened arrays)
print("\nOuter product:")
print(np.outer(x.flatten(), y.flatten()))

# Cartesian product (using meshgrid)
print("\nCartesian product (using meshgrid):")
x_flat = x.flatten()
y_flat = y.flatten()
cartesian = np.array(np.meshgrid(x_flat, y_flat)).T.reshape(-1, 2)
print(f"Shape: {cartesian.shape}")
print("First 10 pairs:")
print(cartesian[:10])

Matrix x:
[[2 3 4]
 [3 2 9]]

Matrix y:
[[ 1  5  0]
 [ 5 10  3]]

Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product (using meshgrid):
Shape: (36, 2)
First 10 pairs:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]]


## Q2: Based on NumPy Mathematics and Statistics

### (a) Array operations - absolute value and percentiles

In [10]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Original array:")
print(array)

# i. Element-wise absolute value
print("\ni. Element-wise absolute value:")
print(np.abs(array))

# ii. Percentiles
flattened = array.flatten()
print(f"\nii. Percentiles:")
print(f"Flattened array: {flattened}")
print(f"25th percentile (flattened): {np.percentile(flattened, 25)}")
print(f"50th percentile (flattened): {np.percentile(flattened, 50)}")
print(f"75th percentile (flattened): {np.percentile(flattened, 75)}")

print(f"\nFor each column:")
print(f"25th percentile: {np.percentile(array, 25, axis=0)}")
print(f"50th percentile: {np.percentile(array, 50, axis=0)}")
print(f"75th percentile: {np.percentile(array, 75, axis=0)}")

print(f"\nFor each row:")
print(f"25th percentile: {np.percentile(array, 25, axis=1)}")
print(f"50th percentile: {np.percentile(array, 50, axis=1)}")
print(f"75th percentile: {np.percentile(array, 75, axis=1)}")

# iii. Mean, Median, Standard Deviation
print(f"\niii. Statistical measures:")
print(f"Mean (flattened): {np.mean(flattened):.2f}")
print(f"Median (flattened): {np.median(flattened):.2f}")
print(f"Standard Deviation (flattened): {np.std(flattened):.2f}")

print(f"\nFor each column:")
print(f"Mean: {np.mean(array, axis=0)}")
print(f"Median: {np.median(array, axis=0)}")
print(f"Standard Deviation: {np.std(array, axis=0)}")

print(f"\nFor each row:")
print(f"Mean: {np.mean(array, axis=1)}")
print(f"Median: {np.median(array, axis=1)}")
print(f"Standard Deviation: {np.std(array, axis=1)}")

Original array:
[[ 1 -2  3]
 [-4  5 -6]]

i. Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

ii. Percentiles:
Flattened array: [ 1 -2  3 -4  5 -6]
25th percentile (flattened): -3.5
50th percentile (flattened): -0.5
75th percentile (flattened): 2.5

For each column:
25th percentile: [-2.75 -0.25 -3.75]
50th percentile: [-1.5  1.5 -1.5]
75th percentile: [-0.25  3.25  0.75]

For each row:
25th percentile: [-0.5 -5. ]
50th percentile: [ 1. -4.]
75th percentile: [2.  0.5]

iii. Statistical measures:
Mean (flattened): -0.50
Median (flattened): -0.50
Standard Deviation (flattened): 3.86

For each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

For each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


### (b) Floor, ceiling, truncated and rounded values

In [11]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Original array:", a)

print(f"\nFloor values: {np.floor(a)}")
print(f"Ceiling values: {np.ceil(a)}")
print(f"Truncated values: {np.trunc(a)}")
print(f"Rounded values: {np.round(a)}")

Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


## Q3: Based on Searching and Sorting

### (a) Array sorting operations

In [12]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Original array:", array)

# i. Sorted array
sorted_array = np.sort(array)
print(f"\ni. Sorted array: {sorted_array}")

# ii. Indices of sorted array
sorted_indices = np.argsort(array)
print(f"ii. Indices of sorted array: {sorted_indices}")

# iii. 4 smallest elements
smallest_4_indices = np.argpartition(array, 3)[:4]
smallest_4 = array[smallest_4_indices]
print(f"iii. 4 smallest elements: {np.sort(smallest_4)}")

# iv. 5 largest elements
largest_5_indices = np.argpartition(array, -5)[-5:]
largest_5 = array[largest_5_indices]
print(f"iv. 5 largest elements: {np.sort(largest_5)[::-1]}")

Original array: [ 10  52  62  16  16  54 453]

i. Sorted array: [ 10  16  16  52  54  62 453]
ii. Indices of sorted array: [0 3 4 1 5 2 6]
iii. 4 smallest elements: [10 16 16 52]
iv. 5 largest elements: [453  62  54  52  16]


### (b) Filter integer and float elements

In [13]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Original array:", array)

# i. Integer elements only (elements that are whole numbers)
integer_mask = array == np.floor(array)
integer_elements = array[integer_mask]
print(f"\ni. Integer elements only: {integer_elements}")

# ii. Float elements only (elements that are not whole numbers)
float_mask = array != np.floor(array)
float_elements = array[float_mask]
print(f"ii. Float elements only: {float_elements}")

Original array: [1.  1.2 2.2 2.  3.  2. ]

i. Integer elements only: [1. 2. 3. 2.]
ii. Float elements only: [1.2 2.2]


## Q4: Image Processing with NumPy

(a) Write a function named img_to_array(path) that reads an image and saves it as text file
(b) Load the saved file into jupyter notebook

In [22]:
# Q4: Image Processing with NumPy
import numpy as np
from PIL import Image
import os

def img_to_array(path):
    """Function to read an image and save it as a text file"""
    try:
        img = Image.open(path)
        img_array = np.array(img)
        base_name = os.path.splitext(os.path.basename(path))[0]
        
        if len(img_array.shape) == 3:  # RGB image
            output_path = f"{base_name}_rgb_array.txt"
            # Save complete RGB image data
            with open(output_path, 'w') as f:
                f.write(f"# RGB Image Array - Shape: {img_array.shape}\n")
                f.write(f"# Data format: Each line contains one pixel's RGB values [R G B]\n")
                for i in range(img_array.shape[0]):
                    for j in range(img_array.shape[1]):
                        f.write(f"{img_array[i, j, 0]} {img_array[i, j, 1]} {img_array[i, j, 2]}\n")
                        
        else:  # Grayscale image
            output_path = f"{base_name}_grayscale_array.txt"
            # Save complete grayscale image data
            np.savetxt(output_path, img_array, fmt='%d', 
                      header=f"Grayscale Image Array - Shape: {img_array.shape}")
        
        return img_array, output_path
    except Exception as e:
        print(f"Error: {e}")
        return None

# (a) Process the image
image_path = "image.png"
result = img_to_array(image_path)

if result:
    img_array, saved_path = result
    print(f"Image shape: {img_array.shape}")
    print(f"Data type: {img_array.dtype}")
    print(f"File saved: {saved_path}")
    
    # Check file size to confirm complete data was saved
    file_size = os.path.getsize(saved_path)
    print(f"File size: {file_size} bytes")
    
    if len(img_array.shape) == 3:  # RGB
        expected_lines = img_array.shape[0] * img_array.shape[1] + 2  # +2 for headers
        print(f"Expected data lines: {expected_lines}")

# (b) Load the saved file back
txt_files = [f for f in os.listdir('.') if f.endswith('_array.txt') and 'image' in f]

if txt_files:
    txt_file = txt_files[0]
    print(f"\nLoading: {txt_file}")
    
    if 'grayscale' in txt_file:
        # Load complete grayscale array
        loaded_array = np.loadtxt(txt_file, dtype=int)
        print(f"Loaded grayscale array shape: {loaded_array.shape}")
        print(f"Arrays match: {np.array_equal(img_array, loaded_array)}")
        
    else:
        # Load RGB data
        with open(txt_file, 'r') as f:
            lines = f.readlines()
        
        # Skip header lines and parse RGB data
        data_lines = [line.strip() for line in lines if not line.startswith('#')]
        rgb_data = []
        for line in data_lines:
            if line:
                rgb_values = [int(x) for x in line.split()]
                rgb_data.append(rgb_values)
        
        # Reconstruct the array
        if rgb_data:
            loaded_rgb = np.array(rgb_data).reshape(img_array.shape)
            print(f"Loaded RGB array shape: {loaded_rgb.shape}")
            print(f"Arrays match: {np.array_equal(img_array, loaded_rgb)}")
        
    print("Complete image data successfully saved and loaded!")

Image shape: (1064, 1600, 3)
Data type: uint8
File saved: image_rgb_array.txt
File size: 18748504 bytes
Expected data lines: 1702402

Loading: image_rgb_array.txt
Loaded RGB array shape: (1064, 1600, 3)
Arrays match: True
Complete image data successfully saved and loaded!
Loaded RGB array shape: (1064, 1600, 3)
Arrays match: True
Complete image data successfully saved and loaded!
